config/routes.rb
Rails.application.routes.draw do
  root 'sessions#redirect'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  get '/reports/day_detail' => 'reports#day_detail'
  get '/reports/day_summary' => 'reports#day_summary'
  get '/reports/goods_distribution_detail' => 'reports#goods_distribution_detail'
  get '/reports/goods_in_employees' => 'reports#goods_in_employees'
  get '/reports/depletion' => 'reports#depletion'
  get '/reports/weight_diff' => 'reports#weight_diff'
  get '/reports/production_by_employees' => 'reports#production_by_employees'
  get '/reports/production_by_type' => 'reports#production_by_type'
  get '/reports/production_summary' => 'reports#production_summary'
  get '/reports/polish_detail_by_type' => 'reports#polish_detail_by_type'
  get '/reports/polish_detail_by_client' => 'reports#polish_detail_by_client'
  get '/reports/polish_detail_by_order_number' => 'reports#polish_detail_by_order_number'
  get '/reports/polish_detail_by_employees' => 'reports#polish_detail_by_employees'
  get '/reports/polish_summary' => 'reports#polish_summary'
  get '/reports/current_user_balance' => 'reports#current_user_balance'
  get '/reports/client_weight_difference' => 'reports#client_weight_difference'
  get '/reports/client_transactions' => 'reports#client_transactions'
  get '/reports/client_transactions_detail' => 'reports#client_transactions_detail'
  get '/reports/contractor_transactions' => 'reports#contractor_transactions'
  get '/reports/contractor_transactions_detail' => 'reports#contractor_transactions_detail'
  get '/reports/goods_flow' => 'reports#goods_flow'

  get '/records/print' => 'records#print'

  resources :contractors

  resources :departments

  resources :records

  resources :users

  resources :employees

  resources :clients

  resources :products

  resources :profiles, only: [:index, :edit, :update]

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  include Page
  self.page_size = 20
  
  skip_before_action :need_super_permission
  prepend_before_action :need_admin_permission, only: [:show]
  prepend_before_action :need_login, only: [:index, :new, :create, :edit, :update, :destroy, :recent]
  before_action :check_for_account_user, only: [:new, :create, :recent]
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  private def params_or_cookies()
    params[:from_date]   = cookies[:record_filter_from_date]   unless params[:from_date]
    params[:to_date]     = cookies[:record_filter_to_date]     unless params[:to_date]
    params[:record_type] = cookies[:record_filter_record_type] unless params[:record_type]
    params[:user_id]     = cookies[:record_filter_user_id]     unless params[:user_id]
    params[:product_id]  = cookies[:record_filter_product_id]  unless params[:product_id]
    params[:employee_id] = cookies[:record_filter_employee_id] unless params[:employee_id]
    params[:client_id]   = cookies[:record_filter_client_id]   unless params[:client_id]
    params[:particpant_type_id] = cookies[:record_filter_particpant_type_id]   unless params[:particpant_type_id]
    params[:order_number] = cookies[:record_filter_order_number]   unless params[:order_number]

    params[:record_type] = nil if params[:record_type] == '-1'
    params[:user_id]     = nil if params[:user_id] == '-1'
    params[:product_id]  = nil if params[:product_id] == '-1'
    params[:employee_id] = nil if params[:employee_id] == '-1'
    params[:client_id]   = nil if params[:client_id] == '-1'
    params[:particpant_type_id] = nil if params[:particpant_type_id] == ''
    params[:order_number] = nil if params[:order_number] == '*'

    cookies[:record_filter_from_date]   = params[:from_date]
    cookies[:record_filter_to_date]     = params[:to_date]
    cookies[:record_filter_record_type] = params[:record_type]
    cookies[:record_filter_user_id]     = params[:user_id]
    cookies[:record_filter_product_id]  = params[:product_id]
    cookies[:record_filter_employee_id] = params[:employee_id]
    cookies[:record_filter_client_id]   = params[:client_id]
    cookies[:record_filter_particpant_type_id] = params[:particpant_type_id]
    cookies[:record_filter_order_number] = params[:order_number]
  end

  def index
    if is_admin_permission?(session[:permission])
      @is_admin = true
    else
      @no_side_bar = true
      params[:user_id] = session[:user_id]
    end

    params_or_cookies()

    params[:from_date] ||= (Record.first.try(:date) || Time.now.to_date).strftime("%Y-%m-%d")
    params[:to_date] ||= Time.now.to_date.strftime("%Y-%m-%d")
    relations = Record.between_date(params[:from_date], params[:to_date])
    unless params[:user_id].blank?
      user = User.find(params[:user_id])
      relations = relations.where('user_id = ? OR (participant_id = ? AND participant_type = ?)', user, user, user.class.name)
    end
    unless params[:record_type].blank?
      relations = relations.of_type(params[:record_type])
    end
    if params[:particpant_type_id]
      particpant_type, particpant_id = params[:particpant_type_id].split('-')
      unless particpant_type.blank?
        relations = relations.where('participant_type = ? AND participant_id = ?', particpant_type, particpant_id.to_i)
      end
    end
    unless params[:product_id].blank?
      relations = relations.where('product_id = ?', params[:product_id])
    end
    unless params[:employee_id].blank?
      relations = relations.where('employee_id = ?', params[:employee_id])
    end
    unless params[:client_id].blank?
      relations = relations.where('client_id = ?', params[:client_id])
    end
    if params[:order_number]
      relations = relations.where('order_number = ?', params[:order_number])
    end
    @records = relations.order('updated_at DESC').limit(page_size).offset(offset(params[:page]))
    # @prev_page, @next_page = prev_and_next_page(params[:page], relations.count)
    @index = params[:page].to_i
    @index = 1 if @index <1
    @page_num = index_to_page(relations.count)
  end

  # GET /records/1
  # GET /records/1.json
  def show
    if is_admin_permission? session[:permission]
      index = Record.where('created_at >= ?', @record.created_at).count
    else
      index = Record.where('created_at >= ? and (user_id = ? OR (participant_id = ? AND participant_type = ?))', @record.created_at, session[:user_id], session[:user_id], User.name).count
    end
    @page = index_to_page(index)
  end

  # GET /records/new
  def new
    unless params[:sk] = nil
      params[:sk] = 0
    end
    record = Record.find_by(id: params[:record])
    @record = record.try(:dup) || Record.new
    @record.user_id = session[:user_id]
    @record.date = record.try(:date) || Time.now.to_date
    @record.weight = nil
    @record.count = nil
    @record.order_number = ''
    @records = Record.where('user_id = ?', session[:user_id]).order('updated_at DESC').limit(page_size).all
    @new_order_number = create_order_number
  end

  # GET /records/1/edit
  def edit
    index = Record.where('created_at >= ? and (user_id = ? OR (participant_id = ? AND participant_type = ?))', @record.created_at, session[:user_id], session[:user_id], User.name).count
    @page = index_to_page(index)
    if is_admin_permission?(session[:permission])
      return
    end
    if @record.user_id != session[:user_id]
      redirect_to records_url(page: @page), notice: '只能编辑本柜台创建的记录'
    end
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    if !@record.is_polish_receive_type?
      respond_to do |format|
        if @record.save
          format.html { redirect_to new_record_url(record: @record), notice: '记录创建成功' }
          format.json { render :show, status: :created, location: @record }
        else
          format.html { render :new }
          format.json { render json: @record.errors, status: :unprocessable_entity }
        end
      end
    else
      sk_weight = (params[:sk] != nil) ? (params[:sk]) : 0
      respond_to do |format|
        if @record.save
          if sk_weight != 0
            @record = Record.new(record_params)
            @record.weight = sk_weight
            @record.product = get_sk_product
            if @record.save
              format.html { redirect_to new_record_url(record: @record), notice: '记录创建成功' }
              format.json { render :show, status: :created, location: @record }
            else
              format.html { render :new }
              format.json { render json: @record.errors, status: :unprocessable_entity }
            end
          else
            format.html { redirect_to new_record_url(record: @record), notice: '记录创建成功' }
            format.json { render :show, status: :created, location: @record }
          end
        else
          format.html { render :new }
          format.json { render json: @record.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    if session[:permission] > User::PERM_ADMIN and @record.user_id != session[:user_id]
      index = Record.where('created_at >= ? and (user_id = ? OR (participant_id = ? AND participant_type = ?))', @record.created_at, session[:user_id], session[:user_id], User.name).count
      redirect_to records_url(page: index_to_page(index)), notice: '只能更新本柜台创建的记录'
      return
    end

    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: '记录更新成功' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    if session[:permission] > User::PERM_ADMIN and @record.user_id != session[:user_id]
      index = Record.where('created_at >= ? and (user_id = ? OR (participant_id = ? AND participant_type = ?))', @record.created_at, session[:user_id], session[:user_id], User.name).count
      redirect_to records_url(page: index_to_page(index)), notice: '只能删除本柜台创建的记录'
      return
    end

    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: '记录删除成功' }
      format.json { head :no_content }
    end
  end

  #print
  def print
    require "reports_controller.rb"
    @printed_records = []
    ids = params[:ids]

    records = ids.map do |id|
      Record.find(id)
    end
    group = records.group_by do |r|
      r.participant.name
    end

    new_group = {}
    group.each do |key, val|
      new_group[key] = val.group_by do |r|
        r.user.name
      end
    end

    new_group.each do |name, val|
      val.each do |name2, val2|
        row = {
          col1: "组别:#{name}",
          col2: "柜台:#{name2}"
        }
        @printed_records.push(row)
        row = {
          col1: "时间:",
          col2: Time.now.strftime('%Y%m%d %H:%M:%S')
        }
        @printed_records.push(row)
        val2.each do |r|
          row = {
              col1: '摘要:',
              col2: r.product.try(:name)
          }
          @printed_records.push(row)
          title = case
                    when Record::DISPATCH.include?(r.record_type)
                      "交与重量:"
                    when Record::RECEIVE.include?(r.record_type)
                      "收回重量:"
                    else
                      "其他:"
                  end
          row = {
              col1: title,
              col2: r.weight
          }
          @printed_records.push(row)
        end
        row = {
          col1: "余额:",
          col2: val2[0].participant.balance_at_date(Time.now.to_date, val2[0].user)
        }
        @printed_records.push(row)
        @printed_records.push({col1: "====", col2: "===="})

app/helpers/records_helper.rb
module RecordsHelper
  def record_type_options_for_normal
    [Record::TYPE_DISPATCH, Record::TYPE_RECEIVE, Record::TYPE_RETURN].collect do |type|
      [Record::RECORD_TYPES[type], type]
    end
  end
  
  def record_type_options_for_check
    [Record::TYPE_DAY_CHECK, Record::TYPE_MONTH_CHECK].collect do |type|
      [Record::RECORD_TYPES[type], type]
    end
  end
  
  def record_type_options_for_polish
    [Record::TYPE_DISPATCH, Record::TYPE_RECEIVE, Record::TYPE_APPORTION].collect do |type|
      [Record::RECORD_TYPES[type], type]
    end
  end
  
  def record_type_options
    Record::RECORD_TYPES.collect do |type, name|
      [name, type]
    end
  end

  def record_type_options_all
    record_type_map = []
    record_type_map << ['全部', -1]
    record_type_map += record_type_options
  end

  def user_options
    User.all.reject  { |user| is_admin_permission? user.permission }
            .collect { |user| [user.name, user.id] }
  end

  def user_options_all
    user_map = []
    user_map << ['全部', -1]
    user_map += user_options
  end

  def particpant_options_all
    particpant_map = []
    particpant_map << ['全部', '']
    particpant_map += Employee.all.collect do |employee|
      str = "Employee-#{employee.id}"
      [employee.name, str]
    end
    particpant_map += User.all.collect do |user|
      str = "User-#{user.id}"
      [user.name, str]
    end
  end

  def order_number_options_all
    order_num_map = []
    order_num_map << ['全部', '*']
    order_num_map << ['无单号', '']
    order_num_map += Record.order(:order_number).select{|record| record.order_number != ''}.collect do |record|
      unless record.order_number == ''
        [record.order_number, record.order_number]
      end
    end
    order_num_map.uniq
  end

  %w[product user employee client].each do |name|
    class_eval <<-END
      def #{name}_texts
        "#{name}".classify.constantize.all.collect do |#{name}|
          "\#{#{name}.serial_number}-\#{#{name}.name}"
        end
        .to_json
      end
    END
  end

  def participant_texts
    Record::PARTICIPANT_CLASS_NAMES.collect do |class_name|
      class_name.to_s.classify.constantize.all.collect do |row|
        if class_name == :user &&  row.permission < 2
          ''
        else
          "#{row.serial_number}-#{row.name}"
        end
      end.delete_if {|s| s == ''}
    end
    .flatten
    .to_json
  end
end

app/views/records/_filter_record.html.erb
<div id="filter_fields">
  <%= form_tag path, method: :get do %>
    <%= label_tag :date, '日期' %>
    <%= text_field_tag :from_date, params[:from_date] , class: 'date_picker record_date'%>
    <span>至</span>
    <%= text_field_tag :to_date, params[:to_date], class: 'date_picker record_date'%>

    <%= label_tag :record_type_text, '类型' %>
    <%= select_tag :record_type, options_for_select(record_type_options_all, params[:record_type]), class: 'record_type' %>

    <% if is_admin_permission? session[:permission] %>
        <%= label_tag :user_name, '柜台' %>
        <%= select_tag :user_id, options_for_select(user_options_all, params[:user_id]), class: 'record_people' %>
    <% end %>

    <%= label_tag :particpant_name, '交收人' %>
    <%= select_tag :particpant_type_id, options_for_select(particpant_options_all, params[:particpant_type_id]), class: 'record_people' %>

    <%= label_tag :product_name, '摘要' %>
    <%= select_tag :product_id, options_for_select(product_options_all, params[:product_id]) %>

    <%= label_tag :employee_name, '生产者' %>
    <%= select_tag :employee_id, options_for_select(employee_options_all, params[:employee_id]), class: 'record_people' %>

    <%= label_tag :client_name, '客户' %>
    <%= select_tag :client_id, options_for_select(client_options_all, params[:client_id]), class: 'record_people' %>

    <%= label_tag :order_number_name, '单号' %>
    <%= select_tag :order_number, options_for_select(order_number_options_all, params[:order_number]), class: 'record_order' %>

    <%= submit_tag '确定'%>
  <% end %>
</div>

app/views/records/_form.html.erb
<div class="list_view">
  <%= form_for(@record) do |f| %>
    <% if @record.errors.any? %>
      <div id="error_explanation" class="ui-state-error ui-corner-all">
        <ul>
          <% @record.errors.each do |_, message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    
    <%= f.hidden_field :user_id%>
    
    <table>
      <tbody>
        <tr id="type_select">
          <td class="label"><%= f.label :record_type, '类型' %></td>
          <td><%= f.select :record_type, record_type_options %></td>
        </tr>
        <tr id='participant'>
          <td class="label"><%= f.label :participant_text, '交收人' %></td>
          <td class="autocomplete">
            <%= f.text_field :participant_text %>
            <div class="data" style="display: none;"><%= participant_texts %></div>
          </td>
        </tr>
        <tr id="product">
          <td class="label"><%= f.label :product_text, '摘要' %></td>
          <td class="autocomplete">
            <%= f.text_field :product_text %>
            <div class="data" style="display: none;"><%= product_texts %></div>
          </td>
        </tr>
        <tr id="weight">
          <td class="label"><%= f.label :weight, '重量' %></td>
          <td><%= f.text_field :weight %></td>
          <td class="gram"></td>
        </tr>
        <tr id="sk">
          <td class="label">水口</td>
          <td><%= text_field_tag :sk, params[:sk]%></td>
          <td class="gram"></td>
        </tr>
        <tr id="count">
          <td class="label"><%= f.label :count, '件数' %></td>
          <td><%= f.text_field :count %></td>
        </tr>
        <tr id="order_number">
          <td class="label"><%= f.label :order_number, '单号' %></td>
          <td><%= f.text_field :order_number %></td>
          <td><button type='button' id='create_order_number' value='<%= @new_order_number %>'>生成单号</button></td>
        </tr>
        <tr id="client">
          <td class="label"><%= f.label :client_text, '客户' %></td>
          <td class="autocomplete">
            <%= f.text_field :client_text %>
            <div class="data" style="display: none;"><%= client_texts %></div>
          </td>
        </tr>
        <tr id="employee">
          <td class="label"><%= f.label :employee_text, '生产人' %></td>
          <td class="autocomplete">
            <%= f.text_field :employee_text %>
            <div class="data" style="display: none;"><%= employee_texts %></div>
          </td>
        </tr>
        <tr id="date">
          <td class="label"><%= f.label :date_text, '日期' %></td>
          <td class="date_picker"><%= f.text_field :date_text %></td>
        </tr>
      </tbody>
    </table>

    <div class="actions">
      <%= f.submit '提交' %>
    </div>
  <% end %>
</div>

app/views/records/_index.html.erb
<% if notice %>
  <div id="notice" class="ui-state-highlight">
    <%= notice %>
  </div>
<% end %>

<% unless @is_admin %>
  <div class="button_group">
    <%= link_to '新建记录', new_record_path, class: 'button' %>
    <%= link_to '打印记录', records_print_path, class: 'button', id: 'print_records' %>
  </div>
<%else%>
  <div class="button_group">
    <%= link_to '打印记录', records_print_path, class: 'button', id: 'print_records' %>
  </div>
<% end %>

<div class="table_view">
  <%= render partial: 'shared/page_nav', locals: { index: @index, page_num: @page_num, path: records_path } %>
  <%= render 'table'%>
  <%= render partial: 'shared/page_nav', locals: { index: @index, page_num: @page_num, path: records_path } %>
</div>

app/views/records/_table.html.erb
<table>
<thead>
  <tr class="head">
    <th><input name="all_print" type="checkbox" value="" id="select_all_checkbox"/>选择所有 </th>
    <th>日期</th>
    <th>类型</th>
    <th>摘要</th>
    <th>重量</th>
    <th>件数</th>
    <th>柜台</th>
    <th>交收人</th>
    <th>单号</th>
    <th>生产者</th>
    <th>客户</th>
    <th>创建时间</th>
    <th colspan="3" class="action">操作</th>
  </tr>
</thead>

<tbody>
    <% unless @records == nil%>
      <% @records.each do |record| %>
        <% if !@is_admin && record.participant.id == session[:user_id] && record.user_id != session[:user_id] %>
        <tr class="as_participant">
        <% else %>
        <tr class="<%= cycle('odd', 'even') %>">
        <% end %>
          <td><input name="print" type="checkbox" value="<%= record.id %>" />打印</td>
          <td><%= record.date_text %></td>
          <td><%= Record::RECORD_TYPES[record.record_type] %></td>
          <td><%= record.product.try(:name) %></td>
          <td><%= data_with_precision(record.weight) %></td>
          <td><%= record.count %></td>
          <td><%= record.user.name %></td>
          <td><%= record.participant.name %></td>
          <td><%= record.order_number %></td>
          <td><%= record.employee.try(:name) %></td>
          <td><%= record.client.try(:name) %></td>
          <td><%= (record.updated_at+8.hour).strftime('%Y-%m-%d %H:%M:%S').to_s %></td>
          <% if @is_admin %>
            <td class="action"><%= link_to '查看', record %></td>
          <% else %>
            <td class="action"><%= link_to '复制', new_record_path(record: record) %></td>
          <% end %>
          <% if session[:permission] <= User::PERM_ADMIN or session[:user_id] == record.user_id %>
          <td class="action"><%= link_to '编辑', edit_record_path(record) %></td>
          <td class="action"><%= link_to '删除', record, method: :delete, data: { confirm: '你确定删除记录？' } %></td>
          <% else %>
          <td class="action"></td>
          <td class="action"></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
</tbody>
</table>

app/views/records/edit.html.erb
<div class="title">
编辑记录 | <%= link_to '返回', records_path(page: @page) %>
</div>

<%= render 'form' %>

app/views/records/index.html.erb
<%= render partial: 'filter_record', locals: {path: records_path} %>
<%= render 'index' %>

app/views/records/new.html.erb
<% if notice %>
  <div id="notice" class="ui-state-highlight">
    <%= notice %>
  </div>
<% end %>

<div class="title">
新建记录 | <%= link_to '返回', records_path %> | <%= link_to '打印记录', records_print_path, id: 'print_records' %>
</div>

<%= render 'form' %>

<div class="table_view">
  <%= render 'table'%>
</div>

app/views/records/print.html.erb
<html>
  <head>
    <style type="text/css">
      body {
        margin: 0 0;
        padding: 0 0;
      }
      #print_records table {
        border-collapse: collapse;
        border-spacing: 0;
        font-family: "Courier";
        font-size: 12px;
      }

      #print_records table th,
      #print_records table td {
        padding: 2px 4px;
        height: 12px;
      }
      #print_records table td.left {
        text-align: right;
      }
    </style>
  </head>
  <body>
    <div id="print_records">
      <table>
        <thead>
        <tr class="title">
          <th colspan="2">交收记录</th>
        </tr>
        </thead>
        <tbody>
          <% @printed_records.each do |record| %>
          <tr>
            <td class="left">
              <%= record[:col1] %>
            </td>
            <td class="right">
              <%= record[:col2] %>
            </td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/views/records/show.html.erb
<div class="table_view">
  <table>
    <thead>
    <tr>
      <th>日期</th>
      <th>类型</th>
      <th>摘要</th>
      <th>重量</th>
      <th>件数</th>
      <th>柜台</th>
      <th>交收人</th>
      <th>单号</th>
      <th>生产者</th>
      <th>客户</th>
      <th>创建时间</th>
    </tr>
    </thead>

    <tbody>
      <tr>
        <td><%= @record.date_text %></td>
        <td><%= Record::RECORD_TYPES[@record.record_type] %></td>
        <td><%= @record.product.try(:name) %></td>
        <td><%= data_with_precision(@record.weight) %></td>
        <td><%= @record.count %></td>
        <td><%= @record.user.name %></td>
        <td><%= @record.participant.name %></td>
        <td><%= @record.order_number %></td>
        <td><%= @record.employee.try(:name) %></td>
        <td><%= @record.client.try(:name) %></td>
        <td><%= (@record.updated_at+8.hour).strftime('%Y-%m-%d %H:%M:%S').to_s %></td>
      </tr>
    </tbody>
  </table>

  <%= link_to '编辑', edit_record_path(@record) %> |
  <%= link_to '返回', records_path(page: @page) %>
</div>