config/routes.rb
Rails.application.routes.draw do
  root 'sessions#redirect'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  get '/reports/day_detail' => 'reports#day_detail'
  get '/reports/day_summary' => 'reports#day_summary'
  get '/reports/goods_distribution_detail' => 'reports#goods_distribution_detail'
  get '/reports/goods_in_employees' => 'reports#goods_in_employees'
  get '/reports/depletion' => 'reports#depletion'
  get '/reports/weight_diff' => 'reports#weight_diff'
  get '/reports/production_by_employees' => 'reports#production_by_employees'
  get '/reports/production_by_type' => 'reports#production_by_type'
  get '/reports/production_summary' => 'reports#production_summary'
  get '/reports/polish_detail_by_type' => 'reports#polish_detail_by_type'
  get '/reports/polish_detail_by_client' => 'reports#polish_detail_by_client'
  get '/reports/polish_detail_by_order_number' => 'reports#polish_detail_by_order_number'
  get '/reports/polish_detail_by_employees' => 'reports#polish_detail_by_employees'
  get '/reports/polish_summary' => 'reports#polish_summary'
  get '/reports/current_user_balance' => 'reports#current_user_balance'
  get '/reports/client_weight_difference' => 'reports#client_weight_difference'
  get '/reports/client_transactions' => 'reports#client_transactions'
  get '/reports/client_transactions_detail' => 'reports#client_transactions_detail'
  get '/reports/contractor_transactions' => 'reports#contractor_transactions'
  get '/reports/contractor_transactions_detail' => 'reports#contractor_transactions_detail'
  get '/reports/goods_flow' => 'reports#goods_flow'

  get '/records/print' => 'records#print'

  resources :contractors

  resources :departments

  resources :records

  resources :users

  resources :employees

  resources :clients

  resources :products

  resources :profiles, only: [:index, :edit, :update]

end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  MIN_ID = 201
  MAX_ID = Rails.env == 'test' ? 10000 : 1000

  include State
  include SerialNumber
  has_serial_number
  
  has_many :transactions, as: :participant, class_name: 'Record'

  validates :name, presence: { message: '请输入名称'}
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  include Page
  self.page_size = 20
  
  skip_before_action :need_super_permission
  prepend_before_action :need_admin_permission, except: [:index, :show]
  before_action :need_level_3_permission, only: [:index, :show]
  before_action :set_contractor, only: [:show, :edit, :update, :destroy]

  # GET /contractors
  # GET /contractors.json
  def index
    @contractors = Contractor.limit(page_size).offset(offset(params[:page]))
    #@prev_page, @next_page = prev_and_next_page(params[:page], Contractor.count)
    @index = params[:page].to_i
    @index = 1 if @index <1
    @page_num = index_to_page(Contractor.count)
  end

  # GET /contractors/1
  # GET /contractors/1.json
  def show
    index = Contractor.where('created_at <= ?', @contractor.created_at).count
    @page = index_to_page(index)
  end

  # GET /contractors/new
  def new
    @contractor = Contractor.new
  end

  # GET /contractors/1/edit
  def edit
    if @contractor.state == State::STATE_SHADOW
      redirect_to contractors_url, notice: '已回收资源不允许编辑'
    end
  end

  # POST /contractors
  # POST /contractors.json
  def create
    @contractor = Contractor.new(contractor_params)

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: '代工客户创建成功' }
        format.json { render :show, status: :created, location: @contractor }
      else
        format.html { render :new }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contractors/1
  # PATCH/PUT /contractors/1.json
  def update
    respond_to do |format|
      if @contractor.update(contractor_params)
        format.html { redirect_to @contractor, notice: '代工客户更新成功' }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contractors/1
  # DELETE /contractors/1.json
  def destroy
    if @contractor.try_destroy
      message = '代工客户删除成功'
    else
      message = '代工客户资源已回收'
    end
    respond_to do |format|
      format.html { redirect_to contractors_url, notice: message }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contractor
      @contractor = Contractor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contractor_params
      params.require(:contractor).permit(:name)
    end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
  def contractor_options
    Contractor.all.collect { |contractor| [contractor.name, contractor.id] }
  end
end

app/views/contractors/_form.html.erb
<div class="list_view">
  <%= form_for(@contractor) do |f| %>
    <% if @contractor.errors.any? %>
      <div id="error_explanation" class="ui-state-error ui-corner-all">
        <ul>
        <% @contractor.errors.each do |_, message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <table>
      <tbody>
      <% if @contractor.id.present? %>
        <tr>
          <td class="label">编码</td>
          <td><%= @contractor.serial_number %></td>
        </tr>
      <% end %>
      <tr>
        <td class="label"><%= f.label :name, '名称' %></td>
        <td><%= f.text_field :name %></td>
      </tr>
      </tbody>
    </table>

    <div class="actions">
      <%= f.submit '提交' %>
    </div>
  <% end %>
</div>

app/views/contractors/edit.html.erb
<div class="title">
编辑代工客户 | <%= link_to '返回', contractors_path %>
</div>

<%= render 'form' %>

app/views/contractors/index.html.erb
<% if notice %>
  <div id="notice" class="ui-state-highlight">
    <%= notice %>
  </div>
<% end %>

<div class="table_view">
  <% if is_admin_permission? session[:permission] %>
    <%= link_to '新建代工客户', new_contractor_path %>
  <% end %>
  <%= render partial: 'shared/page_nav', locals: { index: @index, page_num: @page_num, path: contractors_path } %>
  <table>
    <thead>
      <tr>
        <th>编号</th>
        <th>名称</th>
        <th colspan="3" class="action">操作</th>
      </tr>
    </thead>

    <tbody>
      <% @contractors.each do |contractor| %>
        <% if contractor.state == State::STATE_SHADOW %>
          <tr class="shadow">
        <% else %>
          <tr>
        <% end %>
          <td><%= contractor.serial_number %></td>
          <td><%= contractor.name %></td>
          <td class="action"><%= link_to '查看', contractor %></td>
          <% if is_admin_permission? session[:permission] %>
            <% if contractor.state == State::STATE_SHADOW %>
              <td class="action"></td>
            <% else %>
              <td class="action"><%= link_to '编辑', edit_contractor_path(contractor) %></td>
            <% end  %>
            <td class="action"><%= link_to '删除', contractor, method: :delete, data: { confirm: '你确定删除代工客户吗？' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= render partial: 'shared/page_nav', locals: { index: @index, page_num: @page_num, path: contractors_path } %>
</div>

app/views/contractors/new.html.erb
<div class="title">
新建代工客户 | <%= link_to '返回', contractors_path %>
</div>

<%= render 'form' %>

app/views/contractors/show.html.erb
<% if notice %>
  <div id="notice" class="ui-state-highlight">
    <%= notice %>
  </div>
<% end %>

<div class="table_view">
  <table>
    <thead>
    <th>编号</th>
    <th>名称</th>
    </thead>
    <tbody>
    <% if @contractor.state == State::STATE_SHADOW %>
    <tr class="shadow">
    <% else %>
    <tr>
    <% end %>
      <td><%= @contractor.serial_number %></td>
      <td><%= @contractor.name %></td>
    </tr>
    </tbody>
  </table>
  <% if is_admin_permission? session[:permission] && @contractor.state != State::STATE_SHADOW %>
    <%= link_to '编辑', edit_contractor_path(@contractor) %> |
  <% end %>
  <%= link_to '返回', contractors_path(page: @page) %>
</div>