config/routes.rb
Rails.application.routes.draw do
  root 'sessions#redirect'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end

  get '/reports/day_detail' => 'reports#day_detail'
  get '/reports/day_summary' => 'reports#day_summary'
  get '/reports/goods_distribution_detail' => 'reports#goods_distribution_detail'
  get '/reports/goods_in_employees' => 'reports#goods_in_employees'
  get '/reports/depletion' => 'reports#depletion'
  get '/reports/weight_diff' => 'reports#weight_diff'
  get '/reports/production_by_employees' => 'reports#production_by_employees'
  get '/reports/production_by_type' => 'reports#production_by_type'
  get '/reports/production_summary' => 'reports#production_summary'
  get '/reports/polish_detail_by_type' => 'reports#polish_detail_by_type'
  get '/reports/polish_detail_by_client' => 'reports#polish_detail_by_client'
  get '/reports/polish_detail_by_order_number' => 'reports#polish_detail_by_order_number'
  get '/reports/polish_detail_by_employees' => 'reports#polish_detail_by_employees'
  get '/reports/polish_summary' => 'reports#polish_summary'
  get '/reports/current_user_balance' => 'reports#current_user_balance'
  get '/reports/client_weight_difference' => 'reports#client_weight_difference'
  get '/reports/client_transactions' => 'reports#client_transactions'
  get '/reports/client_transactions_detail' => 'reports#client_transactions_detail'
  get '/reports/contractor_transactions' => 'reports#contractor_transactions'
  get '/reports/contractor_transactions_detail' => 'reports#contractor_transactions_detail'
  get '/reports/goods_flow' => 'reports#goods_flow'

  get '/records/print' => 'records#print'

  resources :contractors

  resources :departments

  resources :records

  resources :users

  resources :employees

  resources :clients

  resources :products

  resources :profiles, only: [:index, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ERP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag controller.controller_name, 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div id="top_nav">
    <div id="top_nav_intern">
      <ul>
        <% if session[:user_id] %>
          <% if (2..3) === session[:permission] %>
            <li><%= link_to '录入', records_path %></li>
          <% end %>
          <li><%= link_to '报表', reports_day_detail_path %></li>
          <li><%= link_to '管理', user_path(session[:user_id]) %></li>
          <% if session[:user_id] %>
            <li><%= link_to '退出', logout_path, method: :delete %></li>
          <% end %>
        <% end %>
      </ul>
      <% if session[:user_id] and session[:permission] > 1 %>
        <% if is_month_check_day? %>
        <span id="notification">今日月结</span>
        <% end %>
        <span id="balance"></span>
      <% end %>
  </div>
  </div>

  <% unless @no_side_bar or session[:user_id].nil? %>
  <div id="sidebar">
    <ul>
      <% if controller.controller_name == 'reports' %>
        <li><%= link_to '日报表（明细）', reports_day_detail_path %></li>
        <li><%= link_to '日报表（汇总）', reports_day_summary_path %></li>
        <li><%= link_to '柜台称差明细汇总表', reports_weight_diff_path %></li>
        <li><%= link_to '打磨统计表（品种）', reports_polish_detail_by_type_path %></li>
        <li><%= link_to '打磨统计表（客户）', reports_polish_detail_by_client_path %></li>
        <li><%= link_to '打磨统计表（单号）', reports_polish_detail_by_order_number_path %></li>
        <li><%= link_to '打磨统计表（生产组）', reports_polish_detail_by_employees_path %></li>
        <li><%= link_to '打磨统计表（汇总）', reports_polish_summary_path %></li>
        <% if is_admin_permission? session[:permission] %>
          <li><%= link_to '损耗明细汇总表', reports_depletion_path %></li>
          <li><%= link_to '黄金分布表（明细）', reports_goods_distribution_detail_path %></li>
          <li><%= link_to '黄金流量表（汇总）', reports_goods_flow_path %></li>
          <li><%= link_to '员工货物表（明细）', reports_goods_in_employees_path %></li>
          <li><%= link_to '生产统计表（生产组）', reports_production_by_employees_path %></li>
          <li><%= link_to '生产统计表（品种）', reports_production_by_type_path %></li>
          <li><%= link_to '生产统计表（汇总）', reports_production_summary_path %></li>
          <li><%= link_to '客户称差统计表', reports_client_weight_difference_path %></li>
          <li><%= link_to '客户往来台帐（明细）', reports_client_transactions_detail_path %></li>
          <li><%= link_to '客户往来台帐（汇总）', reports_client_transactions_path %></li>
          <li><%= link_to '外工厂往来台帐（明细）', reports_contractor_transactions_detail_path %></li>
          <li><%= link_to '外工厂往来台帐（汇总）', reports_contractor_transactions_path %></li>
        <% end %>
      <% else %>
        <li><%= link_to '我的帐户', user_path(session[:user_id]) %></li>
        <li><%= link_to '产品', products_path  %></li>
        <li><%= link_to '部门', departments_path %></li>
        <li><%= link_to '客户', clients_path %></li>
        <li><%= link_to '代工客户', contractors_path %></li>
        <li><%= link_to '配置', profiles_path%></li>
        <% if is_admin_permission? session[:permission] %>
          <li><%= link_to '用户', users_path %></li>
          <li><%= link_to '员工', employees_path %></li>
          <li><%= link_to '记录', records_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div id="content">
    <%= yield %>
  </div>
</body>
</html>